// Code generated by go generate; DO NOT EDIT.
// Source: gen/gen.go

package mathops

// MathOp performs a math operation on two integers.
type MathOp func(a, b int) int

// Add returns a + b using the '+' operator.
func Add(a, b int) int {
	return a + b
}

// Subtract returns a + b using the '-' operator.
func Subtract(a, b int) int {
	return a - b
}

// Multiply returns a + b using the '*' operator.
func Multiply(a, b int) int {
	return a * b
}

// All returns a map of all available operations.
func All() map[string]MathOp {
	return map[string]MathOp{
		"Add":      Add,
		"Subtract": Subtract,
		"Multiply": Multiply,
	}
}
