// Code generated by "stringer -type=Color"; DO NOT EDIT.

package color

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-0]
	_ = x[Green-1]
	_ = x[Blue-2]
	_ = x[Yellow-3]
	_ = x[Purple-4]
}

const _Color_name = "RedGreenBlueYellowPurple"

var _Color_index = [...]uint8{0, 3, 8, 12, 18, 24}

func (i Color) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Color_index)-1 {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[idx]:_Color_index[idx+1]]
}
